services:
  
  mysql:
    container_name: ulet_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #init path, pri vytvarani dockeru sa zavolaju prislusne skripty
      - ./mysql_db:/var/lib/mysql           #cesta k db - kvoli premazaniu db pri inicializacii skriptov
      - ./mysql/conf.d/my.cnf:/etc/my.cnf   #konfigurak - kvoli defaultnemu encodovaniu na utf-8
    env_file:
      - ./mysql/.env
    build: ./mysql/
    restart: always

  redis:
    container_name: ulet_redis
    image: redis:7.2
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379
  
  php:
    container_name: ulet_php
    build: ./php/
    volumes:
      - ./html:/var/www/html
      - ./php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/config/php.ini-development:/usr/local/etc/php/conf.d/php.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mysql
      - redis
  
  nginx:
    container_name: ulet_nginx
    image: nginx:stable-alpine-slim
    ports:
      - 80:80
      - 443:443 
    expose:
      - 80
      - 443
    volumes:
      - ./html:/var/www/html
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/cert:/etc/nginx/cert
    depends_on:
      - php
  
  adminer:
    container_name: ulet_adminer
    image: dockette/adminer:dg
    depends_on:
      - mysql
    ports:
      - 8080:80
    expose:
      - 8080
    restart: always
